# Generated by Django 3.2 on 2024-01-23 01:32

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType

def create_groups_and_permissions(apps, schema_editor):
    # Create CRUD Users group
    crud_group, _ = Group.objects.get_or_create(name='CRUD Users')
    # Assign permissions (add, change, delete, view) for relevant models

    # Create Read-Only Users group
    readonly_group, _ = Group.objects.get_or_create(name='Read-Only Users')
    # Assign view permissions for relevant models
    
    # Assign permissions to CRUD group
    for model in ['address', 'patient', 'distance']:
        content_type = ContentType.objects.get(app_label='core', model=model)
        permissions = Permission.objects.filter(content_type=content_type)
        crud_group.permissions.set(permissions)

    # Assign view-only permissions to Read-Only group
    for model in ['address', 'patient']:
        content_type = ContentType.objects.get(app_label='core', model=model)
        view_permission = Permission.objects.get(content_type=content_type, codename='view_' + model)
        readonly_group.permissions.add(view_permission)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20240123_0006'),
    ]

    operations = [
        migrations.RunPython(create_groups_and_permissions),
    ]
