# Generated by Django 3.2 on 2024-02-15 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_userprofile_is_editor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
